Messenger_Thesis_1._0/Controllers/ClientController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Messenger_Thesis_1._0.Models;
using Messenger_Thesis_1._0.Data.Model.Interface;
using Messenger_Thesis_1._0.Data.Model;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using System.Net.Mail;
using OfficeOpenXml;
using System.Net;

namespace Messenger_Thesis_1._0.Controllers
{
    public class ClientController : Controller
    {
        private readonly IContractRepository contractRepo;
        private readonly ILetterRepository _letterRepo;
        private readonly IUserRepository _userRepo;
        private readonly IHostingEnvironment _hostingEnvironment;
        private readonly IProjectRepository _projectRepo;

        public ClientController(IContractRepository contractRepo, ILetterRepository letterRepo, IUserRepository userRepo, IHostingEnvironment hostingEnvironment, IProjectRepository projectRepo)
        {
            this.contractRepo = contractRepo;
            _letterRepo = letterRepo;
            _userRepo = userRepo;
            _hostingEnvironment = hostingEnvironment;
            _projectRepo = projectRepo;
        }

        public IActionResult Index()
        {
            var users = _userRepo.GetAll().Where(a => a.Role == "Client" && a.Archived == false).OrderByDescending(a => a.UserID).ToList();
            return View(users);
        }

        public IActionResult ArchivedClientAccounts()
        {
            return View(_userRepo.GetAll().Where(a => a.Archived == true && a.Role == "Client").ToList());
        }

        public IActionResult ArchiveAccountExecute(int id)
        {

            var user = _userRepo.FindUser(a => a.UserID == id);
            user.Archived = true;
            _userRepo.Update(user);

            return new ContentResult
            {
                ContentType = "text/html",
                StatusCode = (int)HttpStatusCode.OK,
                Content = "<html><script>alert('Client Archived Success.'); window.open('../../../../Client/Index','_self')</script></html>"
            };
        }

        public IActionResult UnArchiveAccountExecute(int id)
        {
            var user = _userRepo.FindUser(a => a.UserID == id);
            user.Archived = false;
            _userRepo.Update(user);

            return new ContentResult
            {
                ContentType = "text/html",
                StatusCode = (int)HttpStatusCode.OK,
                Content = "<html><script>alert('Client UnArchived Success.'); window.open('../../../../Client/Index','_self')</script></html>"
            };
        }


        [HttpPost]
        public async Task<IActionResult> NewProject(Project project)
        {
            var email = HttpContext.Session.GetString("Email");
            var client = _userRepo.FindUser(a => a.Email == email);
            var code = Guid.NewGuid().ToString("N");

            Project proj = new Project();
            proj.ContractID = project.ContractID;
            proj.ClientName = HttpContext.Session.GetString("FullName");

            DateTime dt = new DateTime(DateTime.Now.Year, DateTime.Now.Month, client.PickupDay);
            if (dt <= DateTime.Now.Date)
            {
                proj.CurrentDateStart = dt;
            }else
            {
               proj.CurrentDateStart =  dt.AddDays(15);
            }

            proj.Email = client.Email;
            proj.Status = "Pending";
            proj.TypeOfTask = "Pick-up";

            proj.InvoiceDate = DateTime.Now;

            proj.ProjectName = client.CompanyName;
            proj.ProjectCode = code;

            _projectRepo.Create(proj);


            if (project.DepositImage == null || project.DepositImage.Length == 0)
                return Content("File Not Selected");

            string fileExtension = Path.GetExtension(project.DepositImage.FileName);

            if (fileExtension == ".xls" || fileExtension == ".xlsx")
            {

                string uploadsFolder = Path.Combine(_hostingEnvironment.WebRootPath, "");
                var fileName = project.DepositImage.FileName;
                var filePath = Path.Combine(uploadsFolder, fileName);
                var fileLocation = new FileInfo(filePath);

                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    await project.DepositImage.CopyToAsync(fileStream);
                }
                var DataList = new List<ExcelFormat>();
              
                using (ExcelPackage package = new ExcelPackage(fileLocation))
                {
                    ExcelWorksheet workSheet = package.Workbook.Worksheets["Sheet1"];
                    //var workSheet = package.Workbook.Worksheets.First();
                    int totalRows = workSheet.Dimension.Rows;

                    for (int i = 1; i <= totalRows; i++)
                    {
                        if (i == 1)
                            continue;
                        DataList.Add(new ExcelFormat
                        {
                            Name = workSheet.Cells[i, 1].Value.ToString(),
                            Address = workSheet.Cells[i, 2].Value.ToString(),
                            Area = workSheet.Cells[i, 3].Value.ToString()
                        });
                    }
                }
                var contractModel = contractRepo.FindContract(a => a.ContractID == project.ContractID);
                int count = 0;
                foreach (var data in DataList)
                {

                    count++;
                    Letter letter = new Letter();
                    letter.ProjectID = _projectRepo.GetAll().OrderBy(a => a.ProjectID).LastOrDefault().ProjectID;
                    letter.ReceiverName = data.Name;
                    letter.LocationOfDelivery = data.Address + " - " + data.Area;
                    letter.Area = data.Area;
                    letter.Price =contractModel.PricePerQuantity / contractModel.Quantity ;
                    _letterRepo.Create(letter);


                }
               
             
                var defQuantity =  contractModel.Quantity;
                var defPrice = contractModel.PricePerQuantity;
                float price = 0;
                if (count <= defQuantity)
                {
                    price = defPrice;
                }else
                {
                    var roundedValue = count / defQuantity;
                    price += roundedValue * defPrice;
                }

                var projID = _projectRepo.GetAll().OrderBy(a => a.ProjectID).LastOrDefault().ProjectID;
                var projectModel = _projectRepo.FindProject(a => a.ProjectID == projID);
                projectModel.Price = price;
                projectModel.Quantity = count;


                _projectRepo.Update(projectModel);


                return UploadSuccess();
            }
            return UploadSuccess();
        }



            [HttpPost]
        public async Task<IActionResult> ReadExcelFileAsync(int projectid, IFormFile file)
        {
            if (file == null || file.Length == 0)
                return Content("File Not Selected");

            string fileExtension = Path.GetExtension(file.FileName);

            if (fileExtension == ".xls" || fileExtension == ".xlsx")
            {

                string uploadsFolder = Path.Combine(_hostingEnvironment.WebRootPath, "");
                var fileName = file.FileName;
                var filePath = Path.Combine(uploadsFolder, fileName);
                var fileLocation = new FileInfo(filePath);

                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    await file.CopyToAsync(fileStream);
                }
                var DataList = new List<ExcelFormat>();
                var code = Guid.NewGuid().ToString("N");
                using (ExcelPackage package = new ExcelPackage(fileLocation))
                {   
                    ExcelWorksheet workSheet = package.Workbook.Worksheets["Sheet1"];
                    //var workSheet = package.Workbook.Worksheets.First();
                    int totalRows = workSheet.Dimension.Rows;

                    for (int i = 1; i <= totalRows; i++)
                    {
                        DataList.Add(new ExcelFormat
                        {
                            Name = workSheet.Cells[i, 1].Value.ToString(),
                            Address = workSheet.Cells[i, 2].Value.ToString(),
                            Area = workSheet.Cells[i, 3].Value.ToString()
                        });
                    }

             

                }

                int count = 0;
                foreach (var data in DataList)
                {

                    count++;
                    Letter letter = new Letter();
                    letter.ProjectID = projectid;
                    letter.ReceiverName = data.Name;
                    letter.LocationOfDelivery = data.Address + " - " + data.Area;
                    letter.Price = 5;
                    
                    _letterRepo.Create(letter);
                    

                }

            }

            return UploadSuccess();
        }
        public IActionResult ActivateAccount(int id)
        {


            var user = _userRepo.FindUser(a => a.UserID == id);
            user.AccountStatus = "Activated";
            _userRepo.Update(user);

            return new ContentResult
            {
                ContentType = "text/html",
                StatusCode = (int)HttpStatusCode.OK,
                Content = "<html><script>alert('Account Activated'); window.open('../../../../User/Index','_self')</script></html>"
            };
        }
        public IActionResult DisableAccount(int id)
        {

Messenger_Thesis_1._0/Controllers/ContractController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Messenger_Thesis_1._0.Data.Model;
using Messenger_Thesis_1._0.Data.Model.Interface;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Messenger_Thesis_1._0.Controllers
{
    public class ContractController : Controller
    {
        private readonly IUserRepository userRepo;
        private readonly IContractRepository contractRepo;

        public ContractController(IUserRepository userRepo, IContractRepository contractRepo)
        {
            this.userRepo = userRepo;
            this.contractRepo = contractRepo;
        }
        public IActionResult Index()
        {
            return View(contractRepo.GetAll().Where(a => a.Archived == false).ToList());
        }

        public string Add(Contract contract)
        {
            
            contractRepo.Create(contract);
            return "";
        }

        public IActionResult Client()
        {
            var userID = int.Parse( HttpContext.Session.GetString("UserID").ToString() );
             var userModel =   userRepo.FindUser(a => a.UserID == userID);
            return View(contractRepo.GetAll().Where(a => a.CompanyName == userModel.CompanyName && a.UserArchive == false).ToList()); 
        }
        public IActionResult AdminArchivePage()
        {
            return View(contractRepo.GetAll().Where(a => a.Archived == true).ToList());
        }
        public IActionResult ClientArchivedPage()
        {
            var userID = int.Parse(HttpContext.Session.GetString("UserID").ToString());
            var userModel = userRepo.FindUser(a => a.UserID == userID);
            return View(contractRepo.GetAll().Where(a => a.CompanyName == userModel.CompanyName && a.UserArchive == true).ToList()); ;

        }

        public IActionResult AdminArchived(int id) {
            var contr = contractRepo.FindContract(a => a.ContractID ==  id);
            if (contractRepo.FindContract(a => a.ContractID == id).EndDuration <= DateTime.Now )
            {

                contr.Archived = true;
                contractRepo.Update(contr);

                return new ContentResult
                {
                    ContentType = "text/html",
                    StatusCode = (int)HttpStatusCode.OK,
                    Content = "<html><script>alert('Contract Archived Success.'); window.open('../../../../Contract/Index','_self')</script></html>"
                };
            }

            return new ContentResult
            {
                ContentType = "text/html",
                StatusCode = (int)HttpStatusCode.OK,
                Content = "<html><script>alert('Contract Archived Fail.'); window.open('../../../../Contract/Index','_self')</script></html>"
            };


        }



        public IActionResult ClientArchived(int id)
        {
            var contr = contractRepo.FindContract(a => a.ContractID == id);
            if (contractRepo.FindContract(a => a.ContractID == id).EndDuration <= DateTime.Now)
            {
                contr.UserArchive = true;
                contractRepo.Update(contr);
                return new ContentResult
                {
                    ContentType = "text/html",
                    StatusCode = (int)HttpStatusCode.OK,
                    Content = "<html><script>alert('Contract Archived Success.'); window.open('../../../../Contract/Client','_self')</script></html>"
                };
            }

            return new ContentResult
            {
                ContentType = "text/html",
                StatusCode = (int)HttpStatusCode.OK,
                Content = "<html><script>alert('Contract Archived Fail.'); window.open('../../../../Contract/Client','_self')</script></html>"
            };


        }




        public IActionResult AdminUnArchived(int id)
        {
            var contr = contractRepo.FindContract(a => a.ContractID == id);
            if (contractRepo.FindContract(a => a.ContractID == id).EndDuration <= DateTime.Now)
            {

                contr.Archived = false;
                contractRepo.Update(contr);

                return new ContentResult
                {
                    ContentType = "text/html",
                    StatusCode = (int)HttpStatusCode.OK,
                    Content = "<html><script>alert('Contract Archived Success.'); window.open('../../../../Contract/Index','_self')</script></html>"
                };
            }

            return new ContentResult
            {
                ContentType = "text/html",
                StatusCode = (int)HttpStatusCode.OK,
                Content = "<html><script>alert('Contract Archived Fail.'); window.open('../../../../Contract/Index','_self')</script></html>"
            };


        }



        public IActionResult ClientUnArchived(int id)
        {
            var contr = contractRepo.FindContract(a => a.ContractID == id);
            if (contractRepo.FindContract(a => a.ContractID == id).EndDuration <= DateTime.Now)
            {
                contr.UserArchive = false;
                contractRepo.Update(contr);
                return new ContentResult
                {
                    ContentType = "text/html",
                    StatusCode = (int)HttpStatusCode.OK,
                    Content = "<html><script>alert('Contract Archived Success.'); window.open('../../../../Contract/Client','_self')</script></html>"
                };
            }

            return new ContentResult
            {
                ContentType = "text/html",
                StatusCode = (int)HttpStatusCode.OK,
                Content = "<html><script>alert('Contract Archived Fail.'); window.open('../../../../Contract/Client','_self')</script></html>"
            };


        }







    }
}

Messenger_Thesis_1._0/Views/Contract/AdminArchivePage.cshtml
@model List<Contract>

@using Messenger_Thesis_1._0.Data.Model.Interface
@inject IUserRepository UserRepository
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Admin.cshtml";
}


    <form id="add_contract">
        <!-- Modal -->
        <div class="modal fade" id="AddContractModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Add Contract</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">

                        <select id="company_name" class="form-control">
                            @{
                                foreach (var m in UserRepository.GetAll().Where(a => a.Role == "Client"))
                                {
                                    <option value="@m.CompanyName">@m.CompanyName</option>
                                }
                            }

                        </select>

                        <label>Quantity</label>
                        <input required tye="number" id="quantity" class="form-control" />

                        <label>Price Per Quantity</label>
                        <input required tye="number" id="price_per_quantity" class="form-control" />

                        <label>Contract Start</label>
                        <div id="parentBirthdate" class="form-group">
                            <div class="input-group  input-group-alternative   ">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="ni ni-calendar-grid-58"></i></span>
                                </div>
                                <input required id="contract_start" autocomplete="off" class="form-control datepicker" placeholder="Contract Start" type="text">
                            </div>
                            <small class="birthdateValidation" style="color:#f5365c"></small>
                        </div>



                        <label>Contract Duration</label>
                        <select id="duration" class="form-control">
                            <option value="1">1 year</option>
                            <option value="2">2 years</option>
                            <option value="3">3 years</option>
                            <option value="4">4 years</option>
                            <option value="5">5 years</option>
                        </select>

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <input type="submit" id="contract_submit" class="btn btn-primary"  />
                    </div>
                </div>
            </div>
        </div>
    </form>


<br />
<br />
<br />
<br />
<br />
<br />



<div class="container-fluid mt--7">
    <div class="row">
        <div class="col">
            <div style="padding:1%;" class="card shadow">
                <button style="width:15%;" type="button" class="btn btn-primary" data-toggle="modal" data-target="#AddContractModal">
                    Add Contract
                </button>
                <div class="card-header border-0">

                    <h3 class="mb-0">Contracts</h3>   <br />
                    <a asp-action="Index" asp-controller="Contract" style="width:10%;" class="btn btn-block">  Projects </a>
                </div>
                <div class="table-responsive">

                    <table id="myTable" class="table align-items-center table-flush">
                        <thead class="thead-light">
                            <tr>
                                <th scope="col">Contract ID </th>
                                <th scope="col">Company Name</th>
                                <th scope="col">Quantity</th>
                                <th scope="col">Price Per Quantity</th>
                                <th scope="col">Duration</th>
                                <th>Archive</th>
                            </tr>
                        </thead>


                        <tbody>
                            @{
                                foreach (var m in Model)
                                {
                                                        <tr>
                                                            <td>@m.ContractID</td>
                                                            <td>@m.CompanyName</td>
                                                            <td>@m.Quantity</td>

                                                            <td>@m.PricePerQuantity</td>
                                                            <td>
                                                                @m.StartDuration.ToShortDateString() - @m.EndDuration.ToShortDateString()
                                                            </td>
                                                            <td>
                                                                @{

                                                                    if (@m.EndDuration <= DateTime.Now)
                                                                    {
                                                                        <a class="btn btn-block" asp-action="AdminUnArchived" asp-controller="Contract" asp-route-id="@m.ContractID"> UnArchive</a>
                                                                    }
                                                                }
                                                            </td>
                                                        </tr>
                                }
                            }



                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


<script>

    document.getElementById('add_contract').onsubmit = function () {
        

        var form = new FormData();

        form.append("CompanyName", $('#company_name').val());
        form.append("Quantity", $('#quantity').val());
        form.append("PricePerQuantity", $('#price_per_quantity').val());
        form.append("YearsOfDuration", $('#duration').val());
        form.append("StartDuration", $('#contract_start').val() );
    
        var XML = new XMLHttpRequest();

        XML.open("POST", "/Contract/Add");
        XML.send(form);

         XML.onreadystatechange = function (e) {

             if (XML.readyState == 4 && XML.status == 200) {

                 Swal.fire({
                     title: 'Success!',
                     text: "Contract Added",
                     icon: 'success',
                     confirmButtonText: 'Okay'
                 }).then((result) => {
                     if (result.value) {

                         window.open("/Contract", "_self");


                     }
                 });

                  $(".modal-backdrop").hide();
                 $("#AddContractModal").hide();
                
             }

        }


        return false;
    }

    $(document).ready(function () {
        var table = $('#myTable').DataTable({
       order : [[ 0, "desc" ]],
            responsive: true,
            dom: 'lBfrtip',
            buttons: [
                {
                    extend: 'print',

                    customize: function (win) {
                        $(win.document.body)
                            .css({ 'font-size': '10pt' })
                            .prepend(
                                '<img style= src="~/logo.png"  style="position:absolute; height:500px; z-index:5000; width:500px; top:0; left:0;" />'
                            );
                    }
                }
            ],
            drawCallback: function () {

                var next = $("#myTable_next > a");
                next.text('>');

                var ss = $("#myTable_previous > a");
                ss.text('<');
            }

        });
        $('.custom-select').removeClass("custom-select");
    });


</script>














<script>

    $("#contract_form").submit(function (e) {

        e.preventDefault();

        var rating = 2;
        var subject = $('#subject').val();
        var message = $('#message').val();

        if (rating == undefined || subject == "" || message == "") {
            $('#validation').html('<div class="alert alert-warning"><strong>Warning!</strong> Please complete the fields below</div>');
            return false;
        } else {
            $('#validation').html("");
        }



        var feedbackModel = new FormData();

        feedbackModel.append("Rating", rating);
        feedbackModel.append("Subject", subject);
        feedbackModel.append("Message", message);

        feedbackModel.append("Behaviour", $('.third-rating').text());
        feedbackModel.append("Promptness", $('.second-rating').text());
        feedbackModel.append("Quality", $('.first-rating').text());
        feedbackModel.append("Responsiveness", $('.fourth-rating').text());


        var sender = new XMLHttpRequest();
        sender.open("POST", "/Feedback/MemberFeedback");
        sender.send(feedbackModel);
        sender.onreadystatechange = function () {
            if (sender.readyState == 4 && sender.status == 200) {
                $(".first").starRating('setRating', 0);
                $(".second").starRating('setRating', 0);
                $(".third").starRating('setRating', 0);
                $(".fourth").starRating('setRating', 0);

                $('#subject').val("");
                $('#message').val("");
                $('#validation').html('<div class="alert alert-success"><strong>Success</strong> Your feedback has been submitted</div>');
            }
        }



    });
</script>
<script src="~/assets/js/plugins/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
<script src="~/rate.js"></script>
<script>
    $(document).ready(function () {
    
    var dateToday = new Date(); 
    $('.datepicker').datepicker({
        startDate : dateToday
    });

        });


</script>

Messenger_Thesis_1._0/Views/Contract/Client.cshtml
@model List<Contract>
@{
    ViewData["Title"] = "Client";
    Layout = "~/Views/Shared/_Admin.cshtml";
}


<div class="container-fluid mt--7">
    <div class="row">
        <div class="col">
            <div style="padding:1%;" class="card shadow">
             
                <div class="card-header border-0">

                    <h3 class="mb-0">Contract of Client</h3>
                    <br />
                    <a asp-action="ClientArchivedPage" asp-controller="Contract" style="width:10%;" class="btn btn-block"> Archive Projects </a>
                </div>
                <div class="table-responsive">

                    <table id="myTable" class="table align-items-center table-flush">
                        <thead class="thead-light">
                            <tr>
                                <th scope="col">Company Name</th>
                                <th scope="col">Quantity</th>
                                <th scope="col">Price Per Quantity</th>
                                <th scope="col">Duration</th>
                                <th>Archive</th>
                            </tr>
                        </thead>


                        <tbody>
                            @{
                                foreach (var m in Model)
                                {
                                    string v = String.Format("{0:D6}", m.ContractID);
                                                        <tr>

                                                            <td>@Html.Raw("MM")@v</td>
                                                            <td>@m.Quantity</td>
                                                            <td>
                                                                @m.StartDuration.ToShortDateString() - @m.EndDuration.ToShortDateString()
                                                            </td>
                                                            <td>@m.PricePerQuantity</td>
                                                            <td>
                                                                @{


                                                                    if (@m.EndDuration <= DateTime.Now)
                                                                    {
                                                                        <a class="btn btn-block" asp-action="ClientArchived" asp-controller="Contract" asp-route-id="@m.ContractID" onclick="return confirm('Are you sure you want to archive this contract?')"> Archive</a>
                                                                    }
                                                                }
                                                            </td>
                                                        </tr>
                                }
                            }



                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


<script>

    

    $(document).ready(function () {
        var table = $('#myTable').DataTable({
             order : [[ 0, "desc" ]],
            responsive: true,
            dom: 'lBfrtip',
            buttons: [
                {
                    extend: 'print',

                    customize: function (win) {
                        $(win.document.body)
                            .css({ 'font-size': '10pt' })
                            .prepend(
                                '<img style= src="~/logo.png"  style="position:absolute; height:500px; z-index:5000; width:500px; top:0; left:0;" />'
                            );
                    }
                }
            ],
            drawCallback: function () {

                var next = $("#myTable_next > a");
                next.text('>');

                var ss = $("#myTable_previous > a");
                ss.text('<');
            }

        });
        $('.custom-select').removeClass("custom-select");
    });


</script>